# Programa Ingenias+ Data Science

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [9]:
import numpy as np

In [2]:
#ejercicio 1
nuevo_arreglo = np.zeros(12)
print(nuevo_arreglo)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#ejercicio 2
arreglo_2 = np.zeros(10)
arreglo_2[4] = 10
print(arreglo_2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [4]:
#ejercicio 3
arreglo3 = np.arange(10, 50)
arreglo3


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
#ejercicio 4
arreglo4 = np.arange (0, 9)
arreglo4.shape = (3, 3)
print(arreglo4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
#ejercicio 5
arreglo5= np.random.randint(0, 100, 100)
print(arreglo5)

[59  1  2 52 61 66 47 48 52 48 50 44 96 29 27 71 27 54 18 92 14 72 70 40
 65 97 97 40 82 72 72 12 43 93 42 16 16 51 57  2 49 16 38  8 26 34 36 47
 81 48 36 13 38 35 14 24 41 26 53 92 97 59 56 62 89 25 51 62 10 73 91 37
 80 49 39 20 87  5 99  3 64 37 14 44 74 66 56 48 10 38 37 89  0  0 55 59
 16 24 88 10]


In [40]:
#media
media = np.mean(arreglo5)
print(media)


46.75


In [41]:
#varianza
varianza = np.var(arreglo5)
varianza

741.6875

In [42]:
#ejercicio 6 Calcular la media de un arreglo usando np.sum
arreglo6 = np.sum(arreglo5)
promedio =arreglo6 / 100
print(promedio)

46.75


In [77]:
#ejercicio 7
funcionvarianza = np.array(arreglo5)
print ((np.sum((funcionvarianza - np.mean(arreglo5))**2)) / len(arreglo5))

741.6875


In [76]:
#ejercicio 8
arreglo8= np.random.randn (1,10, 5)
arreglo8

array([[[-1.13733574, -0.82364561,  0.0357769 ,  2.85536688,
         -2.22703471],
        [ 0.46463303, -0.20235555,  0.90778397,  1.15390694,
         -0.08095143],
        [-0.38251811,  0.10769196, -1.14502812,  0.54923026,
         -0.36715994],
        [-0.84258387, -0.06396073,  0.22234733, -0.87392311,
         -1.01162011],
        [-0.38796998, -2.22615408, -1.13118226,  1.96249237,
         -1.43083605],
        [-1.41286106,  0.52614523,  0.13557067,  0.40255874,
         -0.88158895],
        [ 2.10612993, -0.2730023 ,  0.41049257, -0.13545806,
          2.08618071],
        [ 1.37402251,  0.76905126, -0.23478874,  2.15985473,
         -0.2085008 ],
        [ 0.16337302, -0.98508424, -0.77592587, -0.84052566,
          0.93504483],
        [ 0.61634636,  0.82563842,  1.05458965, -1.58243189,
          0.57190854]]])